version: '3'
services:
  metabolomicsusi-web:
    networks:
      - default
      - nginx-net
    environment:
      VIRTUAL_HOST: metabolomics-usi.ucsd.edu
      VIRTUAL_PORT: 5087
      LETSENCRYPT_HOST: metabolomics-usi.ucsd.edu
      LETSENCRYPT_EMAIL: miw023@ucsd.edu
    command: /app/run_server.sh

networks:
  nginx-net:
    external:
      name: nginx-net