version: '3'
services:
  metabolomicsusi-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: metabolomicsusi-web
    ports:
    - "5087:5000"
    volumes:
        - ./temp:/app/temp:rw
        - ./logs/:/app/logs:rw
    networks:
      - default
    restart: on-failure
    command: /app/run_dev_server.sh

  metabolomicsusi-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: metabolomicsusi-worker
    volumes:
      - ./temp:/app/temp:rw
      - ./logs:/app/logs:rw
    command: /app/run_worker.sh
    restart: unless-stopped
    depends_on: 
      - metabolomicsusi-redis
      - metabolomicsusi-rabbitmq
    networks:
      - default
      - nginx-net

  metabolomicsusi-rabbitmq:
    container_name: metabolomicsusi-rabbitmq
    image: rabbitmq
    networks:
      - default

  metabolomicsusi-redis:
    container_name: metabolomicsusi-redis
    image: redis
    networks:
      - default
  
networks:
  nginx-net:
    external:
      name: nginx-net

