version: '3'
services:
  metabolomicsusi-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: metabolomicsusi-web
    ports:
    - "5087:5000"
    volumes:
        - ./output:/output:rw
        - ./logs/:/app/logs
    networks:
      - default
    restart: on-failure
    command: /app/run_dev_server.sh


